# setup-telegram-control.ps1
# Interactive setup: writes (or updates) MegaArbitrageBot/.env with all
# Telegram Bot Center + Control Center configuration.
#
# Usage:
#   .\scripts\setup-telegram-control.ps1
#   .\scripts\setup-telegram-control.ps1 -BotToken "..." -AdminChatIds "123,456" -AdminToken "..."
#   .\scripts\setup-telegram-control.ps1 -SkipWrite   # preview only, no file written
param(
  [string]$BotToken          = '',
  [string]$PrimaryChatId     = '',
  [string]$AdminChatIds      = '',
  [string]$NotifyChatIds     = '',
  [string]$ControlCenterUrl  = 'https://ultimate-arbitrage-hft.zedanazad43.workers.dev',
  [string]$AdminToken        = '',
  [switch]$SkipWrite,
  [switch]$NoPrompt
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'common.ps1')

$isNonInteractive = $NoPrompt -or (Test-NonInteractiveBotSession)

# ── Resolve values ────────────────────────────────────────────────────────────

$resolvedBotToken = Resolve-BotSetting `
  -ScriptRoot    $PSScriptRoot `
  -Name          'TELEGRAM_BOT_TOKEN' `
  -ExplicitValue $BotToken `
  -PromptMessage 'Enter TELEGRAM_BOT_TOKEN (from @BotFather)' `
  -DisablePrompt:$isNonInteractive

$resolvedChatId = Resolve-BotSetting `
  -ScriptRoot    $PSScriptRoot `
  -Name          'TELEGRAM_CHAT_ID' `
  -ExplicitValue $PrimaryChatId `
  -PromptMessage 'Enter your primary TELEGRAM_CHAT_ID (your own chat ID)' `
  -DisablePrompt:$isNonInteractive

$resolvedAdminChatIds = Resolve-BotSetting `
  -ScriptRoot    $PSScriptRoot `
  -Name          'TELEGRAM_ADMIN_CHAT_IDS' `
  -ExplicitValue $AdminChatIds `
  -PromptMessage "Enter TELEGRAM_ADMIN_CHAT_IDS (comma-separated; leave blank to use TELEGRAM_CHAT_ID)" `
  -DisablePrompt:$isNonInteractive

if ([string]::IsNullOrWhiteSpace($resolvedAdminChatIds) -and -not [string]::IsNullOrWhiteSpace($resolvedChatId)) {
  $resolvedAdminChatIds = $resolvedChatId
}

$resolvedNotifyChatIds = Resolve-BotSetting `
  -ScriptRoot    $PSScriptRoot `
  -Name          'TELEGRAM_NOTIFY_CHAT_IDS' `
  -ExplicitValue $NotifyChatIds `
  -PromptMessage "Enter TELEGRAM_NOTIFY_CHAT_IDS (comma-separated extra alert recipients; optional)" `
  -DisablePrompt:$isNonInteractive

$resolvedControlUrl = Resolve-BotSetting `
  -ScriptRoot    $PSScriptRoot `
  -Name          'CONTROL_CENTER_BASE_URL' `
  -ExplicitValue $ControlCenterUrl `
  -PromptMessage "Enter CONTROL_CENTER_BASE_URL (default: https://ultimate-arbitrage-hft.zedanazad43.workers.dev)" `
  -DisablePrompt:$isNonInteractive

if ([string]::IsNullOrWhiteSpace($resolvedControlUrl)) {
  $resolvedControlUrl = 'https://ultimate-arbitrage-hft.zedanazad43.workers.dev'
}
$resolvedControlUrl = Get-ValidatedAbsoluteHttpUrl -Name 'CONTROL_CENTER_BASE_URL' -Value $resolvedControlUrl

$resolvedAdminToken = Resolve-BotSetting `
  -ScriptRoot    $PSScriptRoot `
  -Name          'CONTROL_CENTER_ADMIN_TOKEN' `
  -ExplicitValue $AdminToken `
  -PromptMessage 'Enter CONTROL_CENTER_ADMIN_TOKEN (your UltimateArbitrageBot ADMIN_TOKEN)' `
  -DisablePrompt:$isNonInteractive

# ── Validate required fields ──────────────────────────────────────────────────

if ([string]::IsNullOrWhiteSpace($resolvedBotToken)) {
  throw 'TELEGRAM_BOT_TOKEN is required. Pass -BotToken or set TELEGRAM_BOT_TOKEN in the environment.'
}
if ([string]::IsNullOrWhiteSpace($resolvedChatId)) {
  throw 'TELEGRAM_CHAT_ID is required. Pass -PrimaryChatId or set TELEGRAM_CHAT_ID in the environment.'
}
if ([string]::IsNullOrWhiteSpace($resolvedAdminChatIds)) {
  throw 'TELEGRAM_ADMIN_CHAT_IDS could not be resolved (and no TELEGRAM_CHAT_ID fallback was available).'
}

# ── Build .env content ────────────────────────────────────────────────────────

$envLines = @(
  "# MegaArbitrageBot — Telegram Bot Center + Control Center configuration"
  "# Generated by setup-telegram-control.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
  "# DO NOT COMMIT this file — it is listed in .gitignore"
  ""
  "# ── Telegram Bot Token ───────────────────────────────────────────────────────"
  "# Get yours from @BotFather on Telegram"
  "TELEGRAM_BOT_TOKEN=$resolvedBotToken"
  ""
  "# ── Primary chat ID (you) ────────────────────────────────────────────────────"
  "# Use @userinfobot or /start a conversation and note the id"
  "TELEGRAM_CHAT_ID=$resolvedChatId"
  ""
  "# ── Admin chat IDs (can run /start /stop /live /paper /scan commands) ────────"
  "# Comma-separated. Non-admins receive alert notifications only."
  "TELEGRAM_ADMIN_CHAT_IDS=$resolvedAdminChatIds"
  ""
  "# ── Notification chat IDs (receive trade/error alerts) ───────────────────────"
  "# Optional. Comma-separated. If blank, only TELEGRAM_CHAT_ID receives alerts."
  "TELEGRAM_NOTIFY_CHAT_IDS=$resolvedNotifyChatIds"
  ""
  "# ── Control Center ───────────────────────────────────────────────────────────"
  "# Base URL of the deployed UltimateArbitrageBot Cloudflare Worker"
  "CONTROL_CENTER_BASE_URL=$resolvedControlUrl"
  ""
  "# Admin token required for protected endpoints (/start /stop /scan /mode/live /mode/paper)"
  "# Set this to the same value as your UltimateArbitrageBot ADMIN_TOKEN secret"
  "CONTROL_CENTER_ADMIN_TOKEN=$resolvedAdminToken"
)

# ── Preview ───────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Telegram Control Center Configuration" -ForegroundColor Cyan
Write-Host "════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Bot Token        : $($resolvedBotToken.Substring(0, [Math]::Min(12, $resolvedBotToken.Length)))…" -ForegroundColor White
Write-Host "  Primary Chat ID  : $resolvedChatId" -ForegroundColor White
Write-Host "  Admin Chat IDs   : $resolvedAdminChatIds" -ForegroundColor Yellow
Write-Host "  Notify Chat IDs  : $(if ($resolvedNotifyChatIds) { $resolvedNotifyChatIds } else { '(none)' })" -ForegroundColor White
Write-Host "  Control Center   : $resolvedControlUrl" -ForegroundColor Green
Write-Host "  Admin Token set  : $(if ($resolvedAdminToken) { '✅ yes' } else { '⚠️  no (read-only mode)' })" -ForegroundColor $(if ($resolvedAdminToken) { 'Green' } else { 'Yellow' })
Write-Host "════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

if ($SkipWrite) {
  Write-Host "SkipWrite flag set — .env file was NOT written." -ForegroundColor Yellow
  return
}

# ── Write .env ────────────────────────────────────────────────────────────────

$envFilePath = Get-EnvFilePath -ScriptRoot $PSScriptRoot
$envContent  = $envLines -join "`n"

Set-Content -Path $envFilePath -Value $envContent -Encoding utf8 -NoNewline
Write-Host "✅ .env written to: $envFilePath" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Install dependencies  : pip install -r requirements.txt" -ForegroundColor White
Write-Host "  2. Run the Telegram bot  : .\scripts\run-telegram-bot.ps1" -ForegroundColor White
Write-Host ""
Write-Host "⚠️  Never commit the .env file — it contains your secrets." -ForegroundColor Yellow
