#!/bin/bash
# Fix Binance API Key Format Issue
# This script helps diagnose and fix Binance API key problems

echo "🔧 Binance API Key Format Fix"
echo "=============================="
echo ""
echo "Issue: Binance API key format is invalid"
echo ""
echo "Step 1: Verify Current Keys"
echo "----------------------------"
echo "Run this command to check your current key format:"
echo "  npx wrangler secret list"
echo ""
echo "Binance API keys should be:"
echo "  - API Key: 64 characters (uppercase letters and numbers)"
echo "  - Secret Key: 64 characters (mixed case letters and numbers)"
echo ""
echo "Step 2: Create New API Keys"
echo "----------------------------"
echo "1. Go to Binance API Management:"
echo "   https://www.binance.com/en/my/settings/api-management"
echo ""
echo "2. Create a NEW API key with these settings:"
echo "   ✓ Name: ultimatearbitragehft-production"
echo "   ✓ Enable Reading: ON"
echo "   ✓ Enable Spot & Margin Trading: ON"
echo "   ✓ Enable Futures: ON (if using perps)"
echo "   ✓ Restrict access to trusted IPs only: OFF (unless you have static IP)"
echo "   ✓ Enable Uniswap: OFF"
echo ""
echo "3. Copy BOTH keys immediately (you won't see the secret again!):"
echo "   - API Key (64 chars)"
echo "   - Secret Key (64 chars)"
echo ""
echo "Step 3: Update GitHub Secrets"
echo "------------------------------"
echo "Go to your GitHub repo → Settings → Secrets and variables → Actions"
echo ""
echo "Update these secrets:"
echo "  - BINANCE_API_KEY: [paste your new 64-char API key]"
echo "  - BINANCE_API_SECRET: [paste your new 64-char secret key]"
echo ""
echo "Step 4: Update Cloudflare Worker Secrets"
echo "-----------------------------------------"
echo "Run these commands:"
echo "  npx wrangler secret put BINANCE_API_KEY"
echo "  npx wrangler secret put BINANCE_API_SECRET"
echo ""
echo "Step 5: Verify Permissions"
echo "---------------------------"
echo "After creating keys, verify they have the right permissions:"
echo ""
echo "1. Go back to Binance API Management"
echo "2. Find your new key and check:"
echo "   ✓ Reading: Enabled"
echo "   ✓ Spot & Margin Trading: Enabled"
echo "   ✓ Futures: Enabled (if needed)"
echo ""
echo "Step 6: Test Connectivity"
echo "--------------------------"
echo "Run these commands to verify:"
echo "  npm run diagnose:exchanges"
echo "  npm run smoke:prod"
echo ""
echo "Common Issues & Solutions:"
echo "--------------------------"
echo ""
echo "❌ Issue: 'Invalid API-key, See the common API-key and error codes'"
echo "   ✅ Solution: Key format is wrong - create new key from Binance dashboard"
echo ""
echo "❌ Issue: 'API key does not exist'"
echo "   ✅ Solution: Key not yet activated - wait 1 minute or recreate"
echo ""
echo "❌ Issue: 'IP address not whitelisted'"
echo "   ✅ Solution: Either disable IP restriction in Binance, or use static IP"
echo ""
echo "❌ Issue: 'This IP cannot be used for this endpoint'"
echo "   ✅ Solution: Enable 'Restrict access to trusted IPs only' and add your IP"
echo ""
echo "❌ Issue: 'Signature for this request is not valid'"
echo "   ✅ Solution: Secret key is wrong - double-check you copied it correctly"
echo ""
echo "Security Notes:"
echo "---------------"
echo "⚠️  NEVER commit API keys to git"
echo "⚠️  ALWAYS use GitHub/Cloudflare secrets"
echo "⚠️  Rotate keys monthly for security"
echo "⚠️  Use IP restrictions when possible"
echo "⚠️  Monitor API usage in Binance dashboard"
echo ""