#!/bin/bash
# Fix Bitget WAF/Network Blocking
# This script helps configure static IP egress for Bitget access

echo "🔧 Bitget WAF/Network Blocking Fix"
echo "===================================="
echo ""
echo "Bitget is blocking requests from Cloudflare Workers dynamic IPs."
echo "To fix this, you need a static IP exit point."
echo ""
echo "Option 1: Use a VPS with static IP (Recommended)"
echo "---------------------------------------------------"
echo "1. Rent a VPS with static IP (DigitalOcean, Linode, AWS, etc.)"
echo "2. Set up a simple HTTP proxy on the VPS:"
echo "   sudo apt update && sudo apt install squid -y"
echo "   sudo systemctl start squid"
echo "   sudo systemctl enable squid"
echo ""
echo "3. Configure Squid (/etc/squid/squid.conf):"
echo "   http_port 3128"
echo "   http_access allow all"
echo "   visible_hostname bitget-proxy"
echo ""
echo "4. Restart Squid: sudo systemctl restart squid"
echo ""
echo "5. Get your VPS IP: curl ifconfig.me"
echo ""
echo "6. Whitelist this IP in Bitget:"
echo "   Go to: https://www.bitget.com/account/api/manage"
echo "   Add your VPS IP to the 'Bind IP' field"
echo ""
echo "7. Update Worker environment variables:"
echo "   PROXY_URL=http://YOUR_VPS_IP:3128"
echo "   Or add to PROXY_LIST if using multiple proxies"
echo ""
echo "Option 2: Use Premium Proxy Service"
echo "-------------------------------------"
echo "Services like Bright Data, Oxylabs, or Smartproxy can work only if you expose them through an HTTP gateway URL the Worker can call."
echo ""
echo "1. Sign up for a service and get credentials / gateway endpoint"
echo ""
echo "2. Preferred: set a gateway URL the Worker can call directly:"
echo "   PROXY_URL=https://YOUR-GATEWAY.example.com/proxy"
echo "   Or EXTERNAL_PROXY_URL=https://YOUR-GATEWAY.example.com/proxy"
echo ""
echo "3. If you are using the built-in external proxy manager metadata, also set:"
echo "   npx wrangler secret put EXTERNAL_PROXY_PROVIDER"
echo "   npx wrangler secret put EXTERNAL_PROXY_USERNAME"
echo "   npx wrangler secret put EXTERNAL_PROXY_PASSWORD"
echo ""
echo "4. Optional Worker vars in wrangler.toml:"
echo "   [vars]"
echo "   EXTERNAL_PROXY_PROVIDER = \"bright_data\"  # or oxylabs, smartproxy"
echo "   EXTERNAL_PROXY_URL = \"https://YOUR-GATEWAY.example.com/proxy\""
echo ""
echo "Option 3: Use Cloudflare Zero Trust (Advanced)"
echo "-----------------------------------------------"
echo "Set up Cloudflare Zero Trust with static egress:"
echo "https://developers.cloudflare.com/cloudflare-one/"
echo ""
echo "After Configuration:"
echo "--------------------"
echo "1. Test connectivity: npm run diagnose:exchanges"
echo "2. Run smoke test: npm run smoke:prod"
echo "3. Verify Bitget is accessible"
echo ""